// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizApp_API.Data;

#nullable disable

namespace QuizApp_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizId"));

                    b.Property<string>("AnswerString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorrectAnswerIndex")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuizId");

                    b.ToTable("Quizs");

                    b.HasData(
                        new
                        {
                            QuizId = 1,
                            AnswerString = "Paris;London;Berlin;Rome",
                            CorrectAnswerIndex = 0,
                            Question = "What is the capital of France?"
                        },
                        new
                        {
                            QuizId = 2,
                            AnswerString = "3;4;5;22",
                            CorrectAnswerIndex = 1,
                            Question = "What is 2 + 2?"
                        },
                        new
                        {
                            QuizId = 3,
                            AnswerString = "Earth;Mars;Jupiter;Saturn",
                            CorrectAnswerIndex = 1,
                            Question = "Which planet is known as the Red Planet?"
                        },
                        new
                        {
                            QuizId = 4,
                            AnswerString = "Shakespeare;Dickens;Tolkien;Austen",
                            CorrectAnswerIndex = 0,
                            Question = "Who wrote 'Romeo and Juliet'?"
                        },
                        new
                        {
                            QuizId = 5,
                            AnswerString = "Oxygen;Nitrogen;Carbon Dioxide;Hydrogen",
                            CorrectAnswerIndex = 2,
                            Question = "Which gas do plants absorb from the atmosphere?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
